name: Run Sigrid CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    sigridci:
        runs-on: ubuntu-latest
        # TODO: Remove if once SIGRID_CI_TOKEN or SIGRID_CI_ORG_TOKEN is configured
        if: false
        steps:
            - name: Check out repository
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

            - name: Sigrid CI
              env:
                  SIGRID_CI_TOKEN: ${{ secrets.SIGRID_CI_TOKEN || secrets.SIGRID_CI_ORG_TOKEN }}
              uses: Software-Improvement-Group/sigridci@d391861da89a25e07ba43f6d047d9046eec7256d # v1.7
              with:
                  source: "./packages"
                  customer: mendix
                  system: mendix-web-widgets
                  publishonly: ${{ github.event_name == 'push' }}

            - name: Save Sigrid CI results
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              with:
                  path: "sigrid-ci-output/**"
                  retention-days: 7
                  if-no-files-found: ignore

            - name: "Sigrid pull request feedback"
              if: github.event_name == 'pull_request'
              uses: mshick/add-pr-comment@7c0890544fb33b0bdd2e59467fbacb62e028a096 # v2.8.1
              with:
                  message-id: sigrid
                  message-path: sigrid-ci-output/feedback.md
